// src/constants.ts
export const floatingPokemons = [
    {
        id: 25,
        src: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
        label: 'Pikachu',
        colors: ['#FFD700', '#FFC300', '#FFB300'],
        position: { top: '22%', left: '27%' },
    },
    {
        id: 1,
        src: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png',
        label: 'Bulbasaur',
        colors: ['#A8E6A1', '#6BCB77', '#3D9D50'],
        position: { top: '25%', left: '65%' },
    },
    {
        id: 4,
        src: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
        label: 'Charmander',
        colors: ['#FFA07A', '#FF7F50', '#FF6347'],
        position: { top: '32%', left: '45%' },
    },
    {
        id: 7,
        src: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
        label: 'Squirtle',
        colors: ['#A0E7E5', '#70D6FF', '#45B5E5'],
        position: { top: '40%', left: '15%' },
    },
    {
        id: 39,
        src: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png',
        label: 'Jigglypuff',
        colors: ['#FFD6E8', '#FFB6C1', '#FF69B4'],
        position: { top: '50%', left: '75%' },
    },
    {
        id: 52,
        src: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png',
        label: 'Meowth',
        colors: ['#FCEBB0', '#F5C77B', '#D4A146'],
        position: { top: '60%', left: '30%' },
    },
    {
        id: 133,
        src: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png',
        label: 'Eevee',
        colors: ['#DDB892', '#B08968', '#7F5539'],
        position: { top: '70%', left: '60%' },
    },
    {
        id: 150,
        src: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png',
        label: 'Mewtwo',
        colors: ['#D3C4F3', '#A89BD2', '#7762B5'],
        position: { top: '20%', left: '80%' },
    },
    {
        id: 151,
        src: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png',
        label: 'Mew',
        colors: ['#F8C8DC', '#F5A9C2', '#F28AA6'],
        position: { top: '75%', left: '45%' },
    },
    {
        id: 54,
        src: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png',
        label: 'Psyduck',
        colors: ['#FFE066', '#FFCC00', '#D4B300'],
        position: { top: '22%', left: '55%' },
    },
    {
        id: 92,
        src: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png',
        label: 'Gastly',
        colors: ['#B39DDB', '#9575CD', '#7E57C2'],
        position: { top: '55%', left: '10%' },
    },
    {
        id: 147,
        src: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png',
        label: 'Dratini',
        colors: ['#AED6F1', '#5DADE2', '#3498DB'],
        position: { top: '65%', left: '85%' },
    },
];